[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Transparent"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

#import = [
#      "~/.config/alacritty/themes/themes/xterm.toml"
#      ]

[selection]
save_to_clipboard = true
